apiVersion: v1
kind: ServiceAccount
metadata:
  name: orchestrator-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: orchestrator-binding
subjects:
  - kind: ServiceAccount
    name: orchestrator-sa
    namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin # God Mode permission
  apiGroup: rbac.authorization.k8s.io